# Data Preprocessing

- Feature Selection
- Data split

    - Feature
    - Target

- Standardize features
- Dimensionality Reduction

In [138]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [139]:
df = pd.read_csv('../data/processed/3_engineered_data.csv', sep=';', encoding='utf-8')
df

,SURFACE,TOURNEY_DATE,TOURNEY_LEVEL,PLAYER_0_ID,PLAYER_0_HAND,PLAYER_0_HT,PLAYER_0_AGE,PLAYER_1_ID,PLAYER_1_HAND,PLAYER_1_HT,...,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,PERC_1_WIN_COMBINED,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF,WIN_COMBINED_DIFF
0,Clay,1967-12-28,A,100092,R,185.0,23.1,100035,R,185.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
1,Clay,1967-12-28,A,110991,R,184.0,25.6,100092,R,185.0,...,0.1,0.04,0.02,0.01,0.06,-0.1,-0.04,-0.02,-0.01,-0.06
2,Clay,1967-12-28,A,100035,R,185.0,28.6,114613,U,184.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
3,Clay,1967-12-28,A,100051,R,185.0,27.1,100119,R,183.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
4,Clay,1967-12-28,A,110991,R,185.0,25.6,100070,R,184.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187728,Hard,2024-12-18,F,210460,R,180.0,19.6,210506,R,193.0,...,0.6,0.48,0.46,0.37,0.51,-0.5,-0.44,-0.44,-0.36,-0.45
187729,Hard,2024-12-18,F,209414,R,178.0,20.5,210506,R,193.0,...,0.6,0.48,0.46,0.38,0.51,-0.3,-0.16,-0.10,-0.17,-0.20
187730,Hard,2024-12-18,F,211663,R,185.0,18.3,210530,L,180.0,...,0.5,0.20,0.10,0.05,0.29,0.0,0.24,0.12,0.06,0.10
187731,Hard,2024-12-18,F,210150,R,193.0,19.2,210530,L,180.0,...,0.5,0.20,0.10,0.05,0.29,0.2,0.44,0.46,0.23,0.32
187732,Hard,2024-12-18,F,209950,R,185.0,20.5,210150,R,193.0,...,0.7,0.64,0.56,0.28,0.61,-0.1,-0.12,-0.02,0.27,-0.05

## Feature Selection

- Data analysis done in **data_visualization.ipynb**

In [140]:
df.columns

Index(['SURFACE', 'TOURNEY_DATE', 'TOURNEY_LEVEL', 'PLAYER_0_ID',
       'PLAYER_0_HAND', 'PLAYER_0_HT', 'PLAYER_0_AGE', 'PLAYER_1_ID',
       'PLAYER_1_HAND', 'PLAYER_1_HT', 'PLAYER_1_AGE', 'SCORE', 'BEST_OF',
       'ROUND', 'AGE_DIFF', 'HT_DIFF', '0_WIN_VS_1', '1_WIN_VS_0',
       'TOTAL_MATCHES', '0_WIN_RATE', '1_WIN_RATE', 'WIN_RATE_DIFF',
       'PLAYER_0_RATING', 'PLAYER_1_RATING', 'RATING_DIFF',
       'PLAYER_0_SURFACE_RATING', 'PLAYER_1_SURFACE_RATING',
       'SURFACE_RATING_DIFF', 'PERC_0_WIN_LAST_10', 'PERC_0_WIN_LAST_25',
       'PERC_0_WIN_LAST_50', 'PERC_0_WIN_LAST_100', 'PERC_0_WIN_COMBINED',
       'PERC_1_WIN_LAST_10', 'PERC_1_WIN_LAST_25', 'PERC_1_WIN_LAST_50',
       'PERC_1_WIN_LAST_100', 'PERC_1_WIN_COMBINED', 'LAST_10_WIN_DIFF',
       'LAST_25_WIN_DIFF', 'LAST_50_WIN_DIFF', 'LAST_100_WIN_DIFF',
       'WIN_COMBINED_DIFF'],
      dtype='object')

In [141]:
df = df.drop(df[['SURFACE', 'TOURNEY_LEVEL', 'PLAYER_0_ID',
       'PLAYER_0_HAND', 'PLAYER_0_HT', 'PLAYER_0_AGE', 'PLAYER_1_ID',
       'PLAYER_1_HAND', 'PLAYER_1_HT', 'PLAYER_1_AGE', 'ROUND']], axis=1)

In [142]:
df.describe()

,SCORE,BEST_OF,AGE_DIFF,HT_DIFF,0_WIN_VS_1,1_WIN_VS_0,TOTAL_MATCHES,0_WIN_RATE,1_WIN_RATE,WIN_RATE_DIFF,...,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,PERC_1_WIN_COMBINED,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF,WIN_COMBINED_DIFF
count,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,...,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000
mean,0.501814,3.437323,-0.007160,0.017791,0.590163,0.595713,1.185876,0.212894,0.212577,0.000317,...,0.473231,0.464918,0.444612,0.409033,0.458819,0.000326,0.000191,0.000880,0.000793,0.000438
std,0.499998,0.827478,5.520829,8.618597,1.409492,1.430202,2.416413,0.367780,0.367532,0.544277,...,0.226273,0.214837,0.225284,0.245763,0.211675,0.295626,0.268696,0.274842,0.298866,0.264425
min,0.000000,1.000000,-41.700000,-41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-0.980000,-0.990000,-0.990000
25%,0.000000,3.000000,-3.600000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.300000,0.360000,0.320000,0.180000,0.330000,-0.200000,-0.160000,-0.180000,-0.190000,-0.180000
50%,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.500000,0.480000,0.480000,0.460000,0.470000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,3.000000,3.600000,5.000000,1.000000,1.000000,1.000000,0.333000,0.333000,0.000000,...,0.600000,0.600000,0.600000,0.600000,0.610000,0.200000,0.160000,0.180000,0.190000,0.180000
max,1.000000,5.000000,40.200000,43.000000,30.000000,29.000000,57.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.990000,1.000000,1.000000,1.000000,0.960000,0.980000,0.990000

## Data Split

In [143]:
feature = df.drop('SCORE', axis=1)
feature.head(3)

,TOURNEY_DATE,BEST_OF,AGE_DIFF,HT_DIFF,0_WIN_VS_1,1_WIN_VS_0,TOTAL_MATCHES,0_WIN_RATE,1_WIN_RATE,WIN_RATE_DIFF,...,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,PERC_1_WIN_COMBINED,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF,WIN_COMBINED_DIFF
0,1967-12-28,5,-5.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
1,1967-12-28,3,2.5,-1.0,0.0,0.0,0.0,0.0,0.0,-0.0,...,0.1,0.04,0.02,0.01,0.06,-0.1,-0.04,-0.02,-0.01,-0.06
2,1967-12-28,3,7.4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00

In [144]:
target = df[['SCORE']]
target.value_counts()

SCORE
1        94207
0        93526
Name: count, dtype: int64

In [145]:
feature.to_csv('../data/processed/5.1_data_feature.csv', sep=';', encoding='utf-8', index=False)
target.to_csv('../data/processed/5.1_data_target.csv', sep=';', encoding='utf-8', index=False)

## Standardize Features

#### StandardScaler (mean = 0, std = 1)

In [146]:
scaler = StandardScaler()

In [147]:
feature_std_esc = scaler.fit_transform(feature.drop(['TOURNEY_DATE'], axis=1))
feature_std_esc = pd.DataFrame(feature_std_esc)

In [148]:
feature_std_esc

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,1.888487,-0.994933,-0.002064,-0.418707,-0.416525,-0.490760,-0.578864,-0.578392,-0.000583,-2.036470,...,-2.091422,-2.164056,-1.973571,-1.664340,-2.167572,-0.001103,-0.000711,-0.003203,-0.002652,-0.001656
1,-0.528503,0.454129,-0.118093,-0.418707,-0.416525,-0.490760,-0.578864,-0.578392,-0.000583,-2.036470,...,-1.649476,-1.977868,-1.884794,-1.623651,-1.884118,-0.339369,-0.149579,-0.075972,-0.036112,-0.228564
2,-0.528503,1.341679,0.113964,-0.418707,-0.416525,-0.490760,-0.578864,-0.578392,-0.000583,-2.077725,...,-2.091422,-2.164056,-1.973571,-1.664340,-2.167572,-0.001103,-0.000711,-0.003203,-0.002652,-0.001656
3,-0.528503,1.033753,0.229993,-0.418707,-0.416525,-0.490760,-0.578864,-0.578392,-0.000583,-2.036470,...,-2.091422,-2.164056,-1.973571,-1.664340,-2.167572,-0.001103,-0.000711,-0.003203,-0.002652,-0.001656
4,-0.528503,0.073750,0.113964,-0.418707,-0.416525,-0.490760,-0.578864,-0.578392,-0.000583,-2.066751,...,-2.091422,-2.164056,-1.973571,-1.664340,-2.167572,-0.001103,-0.000711,-0.003203,-0.002652,-0.001656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187728,1.888487,-0.125496,-1.510434,-0.418707,-0.416525,-0.490760,-0.578864,-0.578392,-0.000583,-1.839262,...,0.560252,0.070200,0.068305,-0.158823,0.241790,-1.692434,-1.638255,-1.604129,-1.207207,-1.703467
187729,1.888487,0.037523,-1.742491,0.290770,-0.416525,-0.076922,2.140159,-0.578392,1.836721,-0.717271,...,0.560252,0.070200,0.068305,-0.118134,0.241790,-1.015901,-0.596182,-0.367050,-0.571469,-0.758016
187730,1.888487,-0.125496,0.578078,0.290770,-0.416525,-0.076922,2.140159,-0.578392,1.836721,-0.762889,...,0.118306,-1.233116,-1.529685,-1.460892,-0.797543,-0.001103,0.892494,0.433414,0.198107,0.376524
187731,1.888487,0.037523,1.506306,-0.418707,-0.416525,-0.490760,-0.578864,-0.578392,-0.000583,0.105656,...,0.118306,-1.233116,-1.529685,-1.460892,-0.797543,0.675430,1.636832,1.670494,0.766925,1.208520
187732,1.888487,0.236769,-0.930292,-0.418707,-0.416525,-0.490760,-0.578864,-0.578392,-0.000583,0.291068,...,1.002197,0.814953,0.512191,-0.525030,0.714214,-0.339369,-0.447314,-0.075972,0.900764,-0.190746

In [149]:
feature_std_esc['TOURNEY_DATE'] = feature['TOURNEY_DATE']
feature_std_esc.head(3)

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,TOURNEY_DATE
0,1.888487,-0.994933,-0.002064,-0.418707,-0.416525,-0.49076,-0.578864,-0.578392,-0.000583,-2.036470,...,-2.164056,-1.973571,-1.664340,-2.167572,-0.001103,-0.000711,-0.003203,-0.002652,-0.001656,1967-12-28
1,-0.528503,0.454129,-0.118093,-0.418707,-0.416525,-0.49076,-0.578864,-0.578392,-0.000583,-2.036470,...,-1.977868,-1.884794,-1.623651,-1.884118,-0.339369,-0.149579,-0.075972,-0.036112,-0.228564,1967-12-28
2,-0.528503,1.341679,0.113964,-0.418707,-0.416525,-0.49076,-0.578864,-0.578392,-0.000583,-2.077725,...,-2.164056,-1.973571,-1.664340,-2.167572,-0.001103,-0.000711,-0.003203,-0.002652,-0.001656,1967-12-28

In [150]:
feature_std_esc.describe()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
count,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,...,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05,1.877330e+05
mean,2.582787e-16,1.498804e-17,9.556766e-18,4.360156e-17,6.298004e-17,-4.844618e-17,2.906771e-17,6.782465e-17,2.513146e-17,-3.429990e-15,...,6.298004e-17,-7.388043e-17,-6.782465e-17,-4.844618e-18,1.404939e-16,9.840631e-18,-2.573703e-17,1.468525e-17,8.780870e-18,-1.907568e-17
std,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,...,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00
min,-2.945493e+00,-7.551937e+00,-4.759232e+00,-4.187070e-01,-4.165249e-01,-4.907600e-01,-5.788642e-01,-5.783917e-01,-1.837886e+00,-3.090021e+00,...,-2.091422e+00,-2.164056e+00,-1.973571e+00,-1.664340e+00,-2.167572e+00,-3.383765e+00,-3.722401e+00,-3.568903e+00,-3.315178e+00,-3.745640e+00
25%,-5.285029e-01,-6.507808e-01,-5.822067e-01,-4.187070e-01,-4.165249e-01,-4.907600e-01,-5.788642e-01,-5.783917e-01,-5.826077e-04,-5.673530e-01,...,-7.655851e-01,-4.883636e-01,-5.531356e-01,-9.319266e-01,-6.085732e-01,-6.776352e-01,-5.961816e-01,-6.581271e-01,-6.383890e-01,-6.823804e-01
50%,-5.285029e-01,1.296941e-03,-2.064289e-03,-4.187070e-01,-4.165249e-01,-4.907600e-01,-5.788642e-01,-5.783917e-01,-5.826077e-04,1.571269e-01,...,1.183062e-01,7.020048e-02,1.570820e-01,2.073834e-01,5.282040e-02,-1.102731e-03,-7.112986e-04,-3.202531e-03,-2.651722e-03,-1.656086e-03
75%,-5.285029e-01,6.533747e-01,5.780781e-01,2.907703e-01,2.826790e-01,-7.692236e-02,3.265705e-01,3.276534e-01,-5.826077e-04,6.877172e-01,...,5.602518e-01,6.287645e-01,6.897452e-01,7.770384e-01,7.142140e-01,6.754297e-01,5.947590e-01,6.517220e-01,6.330856e-01,6.790682e-01
max,1.888487e+00,7.282832e+00,4.987160e+00,2.086561e+01,1.986039e+01,2.309799e+01,2.140159e+00,2.142464e+00,1.836721e+00,3.541730e+00,...,2.328034e+00,2.490645e+00,2.465289e+00,2.363934e+00,2.556668e+00,3.381559e+00,3.720978e+00,3.489729e+00,3.276414e+00,3.742327e+00

#### RobustScaler (better with outliers)

In [151]:
robust = RobustScaler()

In [152]:
feature_robust_esc = robust.fit_transform(feature.drop(['TOURNEY_DATE'], axis=1))
feature_robust_esc = pd.DataFrame(feature_robust_esc)

In [153]:
feature_robust_esc['TOURNEY_DATE'] = feature['TOURNEY_DATE']
feature_robust_esc.head(3)

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,TOURNEY_DATE
0,2.0,-0.763889,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.747788,...,-2.000000,-1.714286,-1.095238,-1.678571,0.00,0.000,0.000000,0.000000,0.000000,1967-12-28
1,0.0,0.347222,-0.1,0.0,0.0,0.0,0.0,0.0,-0.0,-1.747788,...,-1.833333,-1.642857,-1.071429,-1.464286,-0.25,-0.125,-0.055556,-0.026316,-0.166667,1967-12-28
2,0.0,1.027778,0.1,0.0,0.0,0.0,0.0,0.0,0.0,-1.780659,...,-2.000000,-1.714286,-1.095238,-1.678571,0.00,0.000,0.000000,0.000000,0.000000,1967-12-28

In [154]:
feature_robust_esc.describe()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
count,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,...,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000,187733.000000
mean,0.437323,-0.000994,0.001779,0.590163,0.595713,1.185876,0.639322,0.638370,0.000317,-0.125194,...,-0.089231,-0.062840,-0.126385,-0.121350,-0.039931,0.000815,0.000597,0.002445,0.002086,0.001216
std,0.827478,0.766782,0.861860,1.409492,1.430202,2.416413,1.104445,1.103701,0.544277,0.796770,...,0.754243,0.895155,0.804585,0.585151,0.755981,0.739065,0.839675,0.763449,0.786490,0.734514
min,-2.000000,-5.791667,-4.100000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-2.587224,...,-1.666667,-2.000000,-1.714286,-1.095238,-1.678571,-2.500000,-3.125000,-2.722222,-2.605263,-2.750000
25%,0.000000,-0.500000,-0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.577243,...,-0.666667,-0.500000,-0.571429,-0.666667,-0.500000,-0.500000,-0.500000,-0.500000,-0.500000,-0.500000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.500000,0.500000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.422757,...,0.333333,0.500000,0.428571,0.333333,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000
max,2.000000,5.583333,4.300000,30.000000,29.000000,57.000000,3.003003,3.003003,1.000000,2.696744,...,1.666667,2.166667,1.857143,1.261905,1.892857,2.500000,3.125000,2.666667,2.578947,2.750000

In [155]:
feature_std_esc.to_csv('../data/processed/5.2_data_feature_std_esc.csv', sep=';', encoding='utf-8', index=False)
feature_robust_esc.to_csv('../data/processed/5.2_data_feature_robust_esc.csv', sep=';', encoding='utf-8', index=False)

## Dimensionality Reduction (Using RobustScaler Dataset)

#### PCA

In [156]:
pca = PCA(n_components=15, svd_solver='arpack', random_state=0)

In [157]:
pca_robust = pca.fit_transform(feature_robust_esc.drop(['TOURNEY_DATE'], axis=1))

In [158]:
pca_robust.shape

(187733, 15)

In [159]:
pca.explained_variance_ratio_.sum()

np.float64(0.9933390477505215)

In [160]:
pca_robust = pd.DataFrame(pca_robust)
pca_robust['TOURNEY_DATE'] = feature['TOURNEY_DATE']
pca_robust

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,TOURNEY_DATE
0,-3.951160,-0.111719,4.322574,0.068662,0.107928,1.112041,0.616423,0.719888,-0.695141,-0.028404,0.608169,-0.028454,0.049258,0.002598,-0.093784,1967-12-28
1,-3.829423,-0.358895,4.048304,0.096652,-0.126584,-0.731900,-0.111335,0.373972,0.336236,0.019632,0.159203,-0.098360,0.118925,0.026080,0.028853,1967-12-28
2,-3.943885,0.026808,4.274866,-0.016315,-0.031845,-0.778547,0.073513,0.308310,1.032122,0.049826,0.287799,-0.001905,0.021293,-0.007737,0.106232,1967-12-28
3,-3.936827,0.032395,4.262079,-0.008624,0.105907,-0.775634,0.072264,0.310952,0.810370,0.045693,0.310346,0.019831,0.030681,-0.001098,0.097192,1967-12-28
4,-3.942464,-0.055840,4.272306,0.032549,0.129535,-0.769884,0.194288,0.252393,0.096002,0.007610,0.290002,-0.018819,0.024373,0.000237,-0.009009,1967-12-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187728,-2.432442,-4.258988,1.348855,0.975319,-1.365680,1.404694,0.079464,0.250351,0.197036,-0.059121,0.429611,-0.335608,0.433009,-0.037768,-0.343652,2024-12-18
187729,-0.226913,-1.285426,0.304171,2.639028,-1.492706,1.031891,0.877805,1.502796,0.138671,-0.929411,0.069029,-0.639540,0.364675,0.041950,-0.089423,2024-12-18
187730,-0.942276,1.540658,1.671506,2.002758,0.537275,1.144987,1.074544,1.519837,0.029963,-0.844123,-0.831190,-0.581905,0.808382,0.330162,0.386827,2024-12-18
187731,-1.831071,3.220502,0.146838,-0.762226,1.239265,1.808061,-0.234162,-0.063363,-0.148836,0.075884,-0.485201,-0.508820,0.708339,0.494323,0.320180,2024-12-18
187732,-0.908630,0.012671,-1.640068,-0.017314,-0.918758,1.823055,-0.935738,0.075858,-0.028170,-0.018286,-0.035885,0.055654,0.354598,-0.501336,-0.413192,2024-12-18

#### LDA

In [161]:
lda = LinearDiscriminantAnalysis(n_components=1)

In [162]:
lda_robust = lda.fit_transform(X=feature_robust_esc.drop(['TOURNEY_DATE'], axis=1), y=target['SCORE'])
lda_robust

array([[-0.28317874],
       [ 0.25371657],
       [ 0.4351312 ],
       ...,
       [-0.60953661],
       [-1.57391004],
       [ 0.03719171]], shape=(187733, 1))

In [163]:
lda_robust = pd.DataFrame(lda_robust)
lda_robust['TOURNEY_DATE'] = feature['TOURNEY_DATE']
lda_robust

               0 TOURNEY_DATE
0      -0.283179   1967-12-28
1       0.253717   1967-12-28
2       0.435131   1967-12-28
3       0.293009   1967-12-28
4       0.061445   1967-12-28
...          ...          ...
187728  2.166645   2024-12-18
187729  0.968379   2024-12-18
187730 -0.609537   2024-12-18
187731 -1.573910   2024-12-18
187732  0.037192   2024-12-18

[187733 rows x 2 columns]

In [164]:
pca_robust.to_csv('../data/processed/5.3_data_feature_robust_pca.csv', sep=';', encoding='utf-8', index=False)
lda_robust.to_csv('../data/processed/5.3_data_feature_robust_lda.csv', sep=';', encoding='utf-8', index=False)